### ISSUE TITLE
CloudFlare API v4 support

### ISSUE THREAD

**Issue by tbjornli** [vexxhost/CloudFlare-API#25]
We are currently using your CloudFlare-API for some of our scripts and we recently received an email from CloudFlare informing us that we are using they API v1 and that it will be deprecated at November 9th.

Do you have any plans on adding support for CloudFlare API v4.

Thank you for this project.

**Comment by DavidAnderson684** [comment]
I was about to ask the same question!

**Comment by ralphioooo** [comment]
Same question here! :)

**Comment by ablears** [comment]
If you need v4, and you haven't used this project yet, try https://github.com/jamesryanbell/cloudflare as an alternative with v4 support.

**Comment by mnaser** [comment]
I think it would be a good idea to move to the V4 API.  Does anyone have any opinions on how this be handled?  Should we have the work done in another branch and release that as version 2.0.0 (as applications that depend on the V1 API will stop working anyways.)

**Comment by itsnotvalid** [comment]
> CloudFlare is removing support for this API on November 9th, 2016. Please use CloudFlare’s API v4 instead. Documentation is available at api.cloudflare.com
https://www.cloudflare.com/docs/client-api.html

Probably for a simple API like this, it's better to move your code to what @ablears suggests.

**Comment by mnaser** [comment]
This repo has been around for a while so ideally I would like to keep the library alive for new releases!

**Comment by lithium720** [comment]
I agree. It would be awesome to get an update on this. It's very simple and useful.
It's a shame cloudflare's API (v4) is so complicated, just to do some of the simplest things takes multiple steps.

**Comment by dotscript** [comment]
i really like this repo hope they do update. i found jamesryanbell/cloudflare was to much, there is a simple v4 support i found https://github.com/lukesUbuntu/cloudflare-api looks pretty new tho.

**Comment by mnaser** [comment]
Hi everyone :)

Thanks for all the comments, we've been really busy these days but I'll mark this as my weekend project.  I think I can have something preliminary on the same basis of this.

While I have someone in this thread, how do we feel about introducing a new dependency to the module to facilitate and make the HTTP handling more robust (library for handling HTTP)?  Or is there a huge importance to the not-a-lot-of-dependency lean API client

Thanks!
Mohammed

**Comment by lithium720** [comment]
The reason I used this in the first place is because it's really simple and doesn't have any extra dependencys. I would suggest keeping it this way but would also be interested in something more robust as you mention. Honestly I would say it's more up to you.

**Comment by lithium720** [comment]
@mnaser

**Comment by tbjornli** [comment]
We're getting closer and closer to November 9th. Any news or updates?

**Comment by mnaser** [comment]
Sorry everyone, I've been quite busy and I haven't had time to put into this.  We no longer use this library internally so I haven't had the bandwidth to get to this.

If someone would like to propose changes to this, I would welcome this, but I don't think we can continue to maintain this. 😞

**Comment by alejodaraio** [comment]
i did an small library just for purge files https://github.com/alejodaraio/cloudflare-php
Cheers & enjoy.

**Comment by MarceloPedra** [comment]
Hello, have anybody take this code to v4? Or can you recommend a well working script to replace this one?

**Comment by labrocca** [comment]
Still want this updated for v4.

**Comment by acs-ferreira** [comment]
For those still searching: https://github.com/cloudflare/cloudflare-php

**Comment by mnaser** [comment]
Thanks for pushing that up, I'll update the README.
